variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_gcc:
  image: gcc
  script:
  - apt-get update -y
  - apt-get install -y cmake make
  - make all test
  when: manual

build_arm:
  image: debian
  script:
  - apt-get update -y
  - apt-get install -y cmake make gcc-arm-none-eabi
  - make all test
  when: manual 

build_alpine:
  image: alpine
  script:
  - apk update
  - apk add gcc cmake musl-dev make bsd-compat-headers linux-headers
  - make all test

