macro(add_subdirectories)
	set(options OPTIONAL GLOB)
	cmake_parse_arguments("" "${options}" "" "" ${ARGN})
	
	#MESSAGE(STATUS "add_subdirectories glob=${_GLOB} ${_UNPARSED_ARGUMENTS}")
	set(paths ${_UNPARSED_ARGUMENTS})
	if(_GLOB)
		file(GLOB paths ${paths})
	endif()
	foreach(p ${paths})
		if(IS_DIRECTORY ${p})
			#MESSAGE(STATUS "add_subdirectories ${p}")
			add_subdirectory(${p})
		endif()
	endforeach()
endmacro()
